### ISSUE TITLE
ImportError: No module named 'settings'

### ISSUE THREAD

**Issue by SauravKanchan** [nikhilkumarsingh/hackerrank-sdk#3]
>>>from hackerrank.HackerRankAPI import HackerRankAPI

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NAVEENCHANDRA\Anaconda3\lib\site-packages\hackerrank_sdk-0.1-py3.5.egg\hackerrank\HackerRankAPI.py", line 4, in <module>
ImportError: No module named 'settings'

**Comment by SauravKanchan** [comment]
My issue was solved when I removed the below line from "hackerranksdk/hackerrank/HackerRankAPI.py"

>>>from settings import RUN_API_ENDPOINT
>>>from settings import LANG_CODE

**Comment by nikhilkumarsingh** [comment]
This has been fixed.
